---
sudo: true
dist: trusty
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - export DOCKER_REPO=$DOCKER_USERNAME/apache
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
      - echo $DOCKER_REPO # remove this line
      - echo $TAG # remove this line
      - docker build -t apache-ubuntu-bionic .
      - docker images # remove this line
      - docker tag apache-ubuntu-bionic $DOCKER_USERNAME/apache-ubuntu-bionic
      - docker push $DOCKER_USERNAME/apache-ubuntu-bionic
    - stage: test githubfoam.apache2
      script:
      - docker run --rm $DOCKER_USERNAME/apache-ubuntu-bionic ansible-galaxy install githubfoam.apache
notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
