---
services: docker

env:
  - distro: ubuntu1904
  - distro: ubuntu1810
  - distro: ubuntu1804
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: ubuntu1204

script:
    - docker pull hello-world
