---
sudo: true
dist: trusty
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - export DOCKER_REPO=$DOCKER_USERNAME/apache
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
      - docker build -f Dockerfile.ubuntu-1804 -t $DOCKER_REPO:$COMMIT .
      - docker images # remove this line
      - docker tag $REPO:$COMMIT $REPO:$TAG
      - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
      - docker images # remove this line
      - docker push $REPO
    - stage: test githubfoam.apache2
      script:
      - docker run --rm $DOCKER_USERNAME/apache-ubuntu-bionic ansible-galaxy install githubfoam.apache
notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
