---
language: ruby

services: docker

env:
  - distro: "ubuntu:18.04"
  - distro: "centos:8"

script:
    - set -x
    - docker build --build-arg OS_IMAGE=centos:8 -t centos8:ping-v1 --file custom.dockerfile .
    - docker images
    - docker run -it centos8:ping-v1 -c 2 www.google.com
