---
services: docker

env:
  - distro: ubuntu1804
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: ubuntu1204

script:
  # Configure test script so we can run extra tests after playbook is run.
  - docker pull hello-world
