---
sudo: required
notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:

    # TESTED OK
    # - name: "deploy microservices  with event driven architecture - bionic"
    #   dist: bionic
    #   language: python
    #   python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #       # - sudo make build-images
    #       - sudo make deploy-microservices
    #   after_success:
    #     - deactivate

    # TESTED OK
    # - name: "deploy microservices  with event driven architecture - focal"
    #   dist: focal
    #   language: python
    #   python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #       # - sudo make build-images
    #       - sudo make deploy-microservices
    #   after_success:
    #     - deactivate

    - name: "build docker fio image - focal"
      dist: focal
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
          - sudo make build-images
      after_success:
        - deactivate

    - name: "build PowerDNS Recursor - focal"
      dist: focal
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
          # - sudo make build-images
          - sudo make build-powerdns
          # - travis_retry travis_wait mvn install
      after_success:
        - deactivate

    - name: "deploy jenkins artifactory - focal"
      dist: focal
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
          - docker-compose ps
          - docker-compose -f scripts/docker-compose.yml build 
          - docker-compose -f scripts/docker-compose.yml up -d
          - docker-compose ps
          - docker-compose stop 
      after_success:
        - deactivate


    - name: "build PowerDNS Recursor tar ball debian 10 buster on focal"
      # dist: focal #Package 'libvirt-bin' has no installation candidate
      dist: bionic
      arch: amd64
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-vagrant
        - sudo make deploy-libvirt
        - sudo make deploy-debian-buster
      after_success:
        - deactivate
        - sudo vagrant destroy -f # required to run Vagrantfile template        
        - sudo rm Vagrantfile # required to run Vagrantfile template 

    - name: "deploy icinga standalone debian 10 buster on focal"
      # dist: focal #Package 'libvirt-bin' has no installation candidate
      dist: bionic
      arch: amd64
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-vagrant
        - sudo make deploy-libvirt
        - sudo make deploy-icinga-standalone
      after_success:
        - deactivate
        - sudo vagrant destroy -f # required to run Vagrantfile template        
        - sudo rm Vagrantfile # required to run Vagrantfile template