---
language: ruby

services: docker

env:
  - distro: "ubuntu:19.04"

script:
    - set -x
    - docker build --build-arg OS_IMAGE=centos:8 -t centos8:ping-v1 --file custom.dockerfile .
    - docker images
    - docker run -it centos8:ping-v1 -c 2 www.google.com
    - docker build --build-arg OS_IMAGE=ubuntu:19.04 -t ubuntu:ping-v2 --file custom.dockerfile .
    - docker images
    - docker run -it ubuntu:ping-v2 -c 2 www.google.com
