FROM ubuntu:20.10

#FIX;stops asking to configure the tzdata
# ENV TZ=Europe/Paris
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


# RUN apt-get -y update && apt-get install -qqy fio \
RUN DEBIAN_FRONTEND=noninteractive apt-get -y update && apt-get install -qqy fio \
   wget \
   libqt5gui5 \
   gnuplot \
   python2.7

VOLUME /data
WORKDIR /data

ENTRYPOINT [ "fio" ]
