name: "Ubuntu docker CI workflow"


on:
  push:
    branches: [ test ]

jobs:



  ubuntu-latest-job:
    name: "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "build docker file"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        # set -eox pipefail #safety for script
        docker build --file custom.dockerfile . --build-arg OS_IMAGE=centos:8 -t centos8:ping-v1 
        docker images
        # docker run -it centos8:ping-v1 -c 2 www.google.com  
    # the input device is not a TTY    
    # - name: "run docker tooling"
    #   run: |
    #     set -x
    #     docker run -it centos8:ping-v1 -c 2 www.google.com     


  ubuntu-1604-job:
    name: "ubuntu-16.04"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "build docker file"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        # set -eox pipefail #safety for script
        docker build --file custom.dockerfile . --build-arg OS_IMAGE=centos:8 -t centos8:ping-v1 
        docker images
        # docker run -it centos8:ping-v1 -c 2 www.google.com  
    # the input device is not a TTY    
    # - name: "run docker tooling"
    #   run: |
    #     set -x
    #     docker run -it centos8:ping-v1 -c 2 www.google.com        

  ubuntu-1804-job:
    name: "ubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "build docker file"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        # set -eox pipefail #safety for script
        docker build --file custom.dockerfile . --build-arg OS_IMAGE=centos:8 -t centos8:ping-v1 
        docker images
        # docker run -it centos8:ping-v1 -c 2 www.google.com  
    # the input device is not a TTY    
    # - name: "run docker tooling"
    #   run: |
    #     set -x
    #     docker run -it centos8:ping-v1 -c 2 www.google.com          

  ubuntu-2004-job:
    name: "ubuntu-20.04"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "build docker file"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        # set -eox pipefail #safety for script
        docker build --file custom.dockerfile . --build-arg OS_IMAGE=centos:8 -t centos8:ping-v1 
        docker images
        # docker run -it centos8:ping-v1 -c 2 www.google.com  
    # the input device is not a TTY    
    # - name: "run docker tooling"
    #   run: |
    #     set -x
    #     docker run -it centos8:ping-v1 -c 2 www.google.com         